// Auto-generated by commands/generate.ts. Do not edit manually.

/** A provided command. */
export interface ICommand {
  readonly id: string
  readonly title: string
  readonly description: string
  readonly keybindings: { key: string, when: string }[]
}

/** Toggles Dance key bindings. */
export const toggle: ICommand & { readonly id: 'dance.toggle' } = {
  id         : 'dance.toggle',
  title      : 'Toggle',
  description: 'Toggles Dance key bindings.',
  keybindings: [],
}
/** Set Dance mode to Normal. */
export const setNormal: ICommand & { readonly id: 'dance.set.normal' } = {
  id         : 'dance.set.normal',
  title      : 'Set mode to Normal',
  description: 'Set Dance mode to Normal.',
  keybindings: [
    { key: 'escape', when: 'editorTextFocus && dance.mode == \'insert\'' },
  ],
}
/** Set Dance mode to Insert. */
export const setInsert: ICommand & { readonly id: 'dance.set.insert' } = {
  id         : 'dance.set.insert',
  title      : 'Set mode to Insert',
  description: 'Set Dance mode to Insert.',
  keybindings: [],
}
/** Switches to normal mode temporarily. */
export const tmpNormal: ICommand & { readonly id: 'dance.tmp.normal' } = {
  id         : 'dance.tmp.normal',
  title      : 'Temporary normal mode',
  description: 'Switches to normal mode temporarily.',
  keybindings: [
    { key: 'Ctrl+v', when: 'editorTextFocus && dance.mode == \'insert\'' },
  ],
}
/** Switches to insert mode temporarily. */
export const tmpInsert: ICommand & { readonly id: 'dance.tmp.insert' } = {
  id         : 'dance.tmp.insert',
  title      : 'Temporary insert mode',
  description: 'Switches to insert mode temporarily.',
  keybindings: [
    { key: 'Ctrl+v', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Start insert before the current selections. */
export const insertBefore: ICommand & { readonly id: 'dance.insert.before' } = {
  id         : 'dance.insert.before',
  title      : 'Insert before',
  description: 'Start insert before the current selections.',
  keybindings: [
    { key: 'i', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Start insert after the current selections. */
export const insertAfter: ICommand & { readonly id: 'dance.insert.after' } = {
  id         : 'dance.insert.after',
  title      : 'Insert after',
  description: 'Start insert after the current selections.',
  keybindings: [
    { key: 'a', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Start insert at line start of each selection. */
export const insertLineStart: ICommand & { readonly id: 'dance.insert.lineStart' } = {
  id         : 'dance.insert.lineStart',
  title      : 'Insert at line start',
  description: 'Start insert at line start of each selection.',
  keybindings: [
    { key: 'Shift+i', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Start insert at line end of each selection. */
export const insertLineEnd: ICommand & { readonly id: 'dance.insert.lineEnd' } = {
  id         : 'dance.insert.lineEnd',
  title      : 'Insert at line end',
  description: 'Start insert at line end of each selection.',
  keybindings: [
    { key: 'Shift+a', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Create new line and start insert below. */
export const insertNewLineBelow: ICommand & { readonly id: 'dance.insert.newLine.below' } = {
  id         : 'dance.insert.newLine.below',
  title      : 'Insert new line below',
  description: 'Create new line and start insert below.',
  keybindings: [
    { key: 'o', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Create new line and start insert above. */
export const insertNewLineAbove: ICommand & { readonly id: 'dance.insert.newLine.above' } = {
  id         : 'dance.insert.newLine.above',
  title      : 'Insert new line above',
  description: 'Create new line and start insert above.',
  keybindings: [
    { key: 'Shift+o', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Add a new line below, without entering insert mode. */
export const newLineBelow: ICommand & { readonly id: 'dance.newLine.below' } = {
  id         : 'dance.newLine.below',
  title      : 'Add new line below',
  description: 'Add a new line below, without entering insert mode.',
  keybindings: [
    { key: 'Alt+o', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Add a new line above, without entering insert mode. */
export const newLineAbove: ICommand & { readonly id: 'dance.newLine.above' } = {
  id         : 'dance.newLine.above',
  title      : 'Add new line above',
  description: 'Add a new line above, without entering insert mode.',
  keybindings: [
    { key: 'Shift+Alt+o', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Repeat last insert-mode change. */
export const repeatInsert: ICommand & { readonly id: 'dance.repeat.insert' } = {
  id         : 'dance.repeat.insert',
  title      : 'Repeat last insert-mode change',
  description: 'Repeat last insert-mode change.',
  keybindings: [
    { key: '.', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Move left. */
export const left: ICommand & { readonly id: 'dance.left' } = {
  id         : 'dance.left',
  title      : 'Move left',
  description: 'Move left.',
  keybindings: [
    { key: 'left', when: 'editorTextFocus && dance.mode == \'normal\'' },
    { key: 'h', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Move right. */
export const right: ICommand & { readonly id: 'dance.right' } = {
  id         : 'dance.right',
  title      : 'Move right',
  description: 'Move right.',
  keybindings: [
    { key: 'right', when: 'editorTextFocus && dance.mode == \'normal\'' },
    { key: 'l', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Move up. */
export const up: ICommand & { readonly id: 'dance.up' } = {
  id         : 'dance.up',
  title      : 'Move up',
  description: 'Move up.',
  keybindings: [
    { key: 'up', when: 'editorTextFocus && dance.mode == \'normal\'' },
    { key: 'k', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Move down. */
export const down: ICommand & { readonly id: 'dance.down' } = {
  id         : 'dance.down',
  title      : 'Move down',
  description: 'Move down.',
  keybindings: [
    { key: 'down', when: 'editorTextFocus && dance.mode == \'normal\'' },
    { key: 'j', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Select to the next character pressed, including it. */
export const selectToIncluded: ICommand & { readonly id: 'dance.select.to.included' } = {
  id         : 'dance.select.to.included',
  title      : 'Select to',
  description: 'Select to the next character pressed, including it.',
  keybindings: [
    { key: 'f', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Select until the next character pressed, excluding it. */
export const selectToExcluded: ICommand & { readonly id: 'dance.select.to.excluded' } = {
  id         : 'dance.select.to.excluded',
  title      : 'Select until',
  description: 'Select until the next character pressed, excluding it.',
  keybindings: [
    { key: 't', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Select whole buffer. */
export const selectBuffer: ICommand & { readonly id: 'dance.select.buffer' } = {
  id         : 'dance.select.buffer',
  title      : 'Select whole buffer',
  description: 'Select whole buffer.',
  keybindings: [
    { key: 'Shift+5', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Select line on which the end of each selection lies (or next line when end lies on an end-of-line). */
export const selectLine: ICommand & { readonly id: 'dance.select.line' } = {
  id         : 'dance.select.line',
  title      : 'Select line',
  description: 'Select line on which the end of each selection lies (or next line when end lies on an end-of-line).',
  keybindings: [
    { key: 'x', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Select to line beginning. */
export const selectToLineBegin: ICommand & { readonly id: 'dance.select.toLineBegin' } = {
  id         : 'dance.select.toLineBegin',
  title      : 'Select to line beginning',
  description: 'Select to line beginning.',
  keybindings: [
    { key: 'Alt+h', when: 'editorTextFocus && dance.mode == \'normal\'' },
    { key: 'home', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Select to line end. */
export const selectToLineEnd: ICommand & { readonly id: 'dance.select.toLineEnd' } = {
  id         : 'dance.select.toLineEnd',
  title      : 'Select to line end',
  description: 'Select to line end.',
  keybindings: [
    { key: 'Alt+l', when: 'editorTextFocus && dance.mode == \'normal\'' },
    { key: 'end', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Select enclosing characters. */
export const selectEnclosing: ICommand & { readonly id: 'dance.select.enclosing' } = {
  id         : 'dance.select.enclosing',
  title      : 'Select enclosing characters',
  description: 'Select enclosing characters.',
  keybindings: [
    { key: 'm', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Extend selections to contain full lines (including end-of-lines). */
export const expandLines: ICommand & { readonly id: 'dance.expandLines' } = {
  id         : 'dance.expandLines',
  title      : 'Extend lines',
  description: 'Extend selections to contain full lines (including end-of-lines).',
  keybindings: [
    { key: 'Alt+x', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Trim selections to only contain full lines (not including last end-of-line). */
export const trimLines: ICommand & { readonly id: 'dance.trimLines' } = {
  id         : 'dance.trimLines',
  title      : 'Trim lines',
  description: 'Trim selections to only contain full lines (not including last end-of-line).',
  keybindings: [
    { key: 'Shift+Alt+x', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Select the word and following whitespaces on the right of the end of each selection. */
export const selectWord: ICommand & { readonly id: 'dance.select.word' } = {
  id         : 'dance.select.word',
  title      : 'Select to next word start',
  description: 'Select the word and following whitespaces on the right of the end of each selection.',
  keybindings: [
    { key: 'w', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Select preceding whitespaces and the word on the left of the end of each selection. */
export const selectWordPrevious: ICommand & { readonly id: 'dance.select.word.previous' } = {
  id         : 'dance.select.word.previous',
  title      : 'Select to previous word start',
  description: 'Select preceding whitespaces and the word on the left of the end of each selection.',
  keybindings: [
    { key: 'b', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Select preceding whitespaces and the word on the right of the end of each selection. */
export const selectWordEnd: ICommand & { readonly id: 'dance.select.word.end' } = {
  id         : 'dance.select.word.end',
  title      : 'Select to next word end',
  description: 'Select preceding whitespaces and the word on the right of the end of each selection.',
  keybindings: [
    { key: 'e', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Select the non-whitespace word and following whitespaces on the right of the end of each selection. */
export const selectWordAlt: ICommand & { readonly id: 'dance.select.word.alt' } = {
  id         : 'dance.select.word.alt',
  title      : 'Select to next non-whitespace word start',
  description: 'Select the non-whitespace word and following whitespaces on the right of the end of each selection.',
  keybindings: [
    { key: 'Alt+w', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Select preceding whitespaces and the non-whitespace word on the left of the end of each selection. */
export const selectWordAltPrevious: ICommand & { readonly id: 'dance.select.word.alt.previous' } = {
  id         : 'dance.select.word.alt.previous',
  title      : 'Select to previous non-whitespace word start',
  description: 'Select preceding whitespaces and the non-whitespace word on the left of the end of each selection.',
  keybindings: [
    { key: 'Alt+b', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Select preceding whitespaces and the non-whitespace word on the right of the end of each selection. */
export const selectWordAltEnd: ICommand & { readonly id: 'dance.select.word.alt.end' } = {
  id         : 'dance.select.word.alt.end',
  title      : 'Select to next non-whitespace word end',
  description: 'Select preceding whitespaces and the non-whitespace word on the right of the end of each selection.',
  keybindings: [
    { key: 'Alt+e', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Select within current selections according to a RegExp. */
export const select: ICommand & { readonly id: 'dance.select' } = {
  id         : 'dance.select',
  title      : 'Select',
  description: 'Select within current selections according to a RegExp.',
  keybindings: [
    { key: 's', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Split within current selections according to a RegExp. */
export const split: ICommand & { readonly id: 'dance.split' } = {
  id         : 'dance.split',
  title      : 'Split',
  description: 'Split within current selections according to a RegExp.',
  keybindings: [
    { key: 'Shift+s', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Split selections into lines. */
export const splitLines: ICommand & { readonly id: 'dance.split.lines' } = {
  id         : 'dance.split.lines',
  title      : 'Split lines',
  description: 'Split selections into lines.',
  keybindings: [
    { key: 'Alt+s', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Select first and last characters of each selection. */
export const selectFirstLast: ICommand & { readonly id: 'dance.select.firstLast' } = {
  id         : 'dance.select.firstLast',
  title      : 'Select first and last characters',
  description: 'Select first and last characters of each selection.',
  keybindings: [
    { key: 'Shift+Alt+s', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Copy selection to next line. */
export const selectCopy: ICommand & { readonly id: 'dance.select.copy' } = {
  id         : 'dance.select.copy',
  title      : 'Copy selection to next line',
  description: 'Copy selection to next line.',
  keybindings: [
    { key: 'Shift+c', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Copy selection to previous line. */
export const selectCopyBackwards: ICommand & { readonly id: 'dance.select.copy.backwards' } = {
  id         : 'dance.select.copy.backwards',
  title      : 'Copy selection to previous line',
  description: 'Copy selection to previous line.',
  keybindings: [
    { key: 'Shift+Alt+c', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Reduce selections to their cursor. */
export const selectionsReduce: ICommand & { readonly id: 'dance.selections.reduce' } = {
  id         : 'dance.selections.reduce',
  title      : 'Reduce selections',
  description: 'Reduce selections to their cursor.',
  keybindings: [
    { key: ';', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Flip the direction of each selection. */
export const selectionsFlip: ICommand & { readonly id: 'dance.selections.flip' } = {
  id         : 'dance.selections.flip',
  title      : 'Flip selections',
  description: 'Flip the direction of each selection.',
  keybindings: [
    { key: 'Alt+;', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Ensure selections are in forward direction (the active cursor is after the anchor). */
export const selectionsForward: ICommand & { readonly id: 'dance.selections.forward' } = {
  id         : 'dance.selections.forward',
  title      : 'Forward selections',
  description: 'Ensure selections are in forward direction (the active cursor is after the anchor).',
  keybindings: [
    { key: 'Shift+Alt+;', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Ensure selections are in backward direction (the active cursor is before the anchor). */
export const selectionsBackward: ICommand & { readonly id: 'dance.selections.backward' } = {
  id         : 'dance.selections.backward',
  title      : 'Backward selections',
  description: 'Ensure selections are in backward direction (the active cursor is before the anchor).',
  keybindings: [],
}
/** Clear selections (except main) */
export const selectionsClear: ICommand & { readonly id: 'dance.selections.clear' } = {
  id         : 'dance.selections.clear',
  title      : 'Clear selections',
  description: 'Clear selections (except main)',
  keybindings: [
    { key: 'space', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Clear main selection. */
export const selectionsClearMain: ICommand & { readonly id: 'dance.selections.clearMain' } = {
  id         : 'dance.selections.clearMain',
  title      : 'Clear main selection',
  description: 'Clear main selection.',
  keybindings: [
    { key: 'Alt+space', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Keep selections that match a RegExp. */
export const selectionsKeepMatching: ICommand & { readonly id: 'dance.selections.keepMatching' } = {
  id         : 'dance.selections.keepMatching',
  title      : 'Keep matching selections',
  description: 'Keep selections that match a RegExp.',
  keybindings: [
    { key: 'Alt+k', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Clear selections that match a RegExp. */
export const selectionsClearMatching: ICommand & { readonly id: 'dance.selections.clearMatching' } = {
  id         : 'dance.selections.clearMatching',
  title      : 'Clear matching selections',
  description: 'Clear selections that match a RegExp.',
  keybindings: [
    { key: 'Shift+Alt+k', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Merge contiguous selections together, including across lines. */
export const selectionsMerge: ICommand & { readonly id: 'dance.selections.merge' } = {
  id         : 'dance.selections.merge',
  title      : 'Merge contiguous selections',
  description: 'Merge contiguous selections together, including across lines.',
  keybindings: [
    { key: 'Shift+Alt+-', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Align selections, aligning the cursor of each selection by inserting spaces before the first character of each selection. */
export const selectionsAlign: ICommand & { readonly id: 'dance.selections.align' } = {
  id         : 'dance.selections.align',
  title      : 'Align selections',
  description: 'Align selections, aligning the cursor of each selection by inserting spaces before the first character of each selection.',
  keybindings: [
    { key: 'Shift+7', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Copy the indentation of the main selection (or the count one if a count is given) to all other ones. */
export const selectionsAlignCopy: ICommand & { readonly id: 'dance.selections.align.copy' } = {
  id         : 'dance.selections.align.copy',
  title      : 'Copy indentation',
  description: 'Copy the indentation of the main selection (or the count one if a count is given) to all other ones.',
  keybindings: [
    { key: 'Shift+Alt+7', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Yank and delete selections. */
export const deleteYank: ICommand & { readonly id: 'dance.delete.yank' } = {
  id         : 'dance.delete.yank',
  title      : 'Yank and delete',
  description: 'Yank and delete selections.',
  keybindings: [
    { key: 'd', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Yank, delete and enter insert mode. */
export const deleteInsertYank: ICommand & { readonly id: 'dance.delete.insert.yank' } = {
  id         : 'dance.delete.insert.yank',
  title      : 'Yank, delete and insert',
  description: 'Yank, delete and enter insert mode.',
  keybindings: [
    { key: 'c', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Delete selections without yanking. */
export const deleteNoYank: ICommand & { readonly id: 'dance.delete.noYank' } = {
  id         : 'dance.delete.noYank',
  title      : 'Delete without yank',
  description: 'Delete selections without yanking.',
  keybindings: [
    { key: 'Alt+d', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Delete selections without yanking and enter insert mode. */
export const deleteInsertNoYank: ICommand & { readonly id: 'dance.delete.insert.noYank' } = {
  id         : 'dance.delete.insert.noYank',
  title      : 'Delete and insert without yank',
  description: 'Delete selections without yanking and enter insert mode.',
  keybindings: [
    { key: 'Alt+c', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Yank selections. */
export const yank: ICommand & { readonly id: 'dance.yank' } = {
  id         : 'dance.yank',
  title      : 'Yank',
  description: 'Yank selections.',
  keybindings: [
    { key: 'y', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Paste after the end of each selection. */
export const pasteAfter: ICommand & { readonly id: 'dance.paste.after' } = {
  id         : 'dance.paste.after',
  title      : 'Paste after',
  description: 'Paste after the end of each selection.',
  keybindings: [
    { key: 'p', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Paste before the start of each selection. */
export const pasteBefore: ICommand & { readonly id: 'dance.paste.before' } = {
  id         : 'dance.paste.before',
  title      : 'Paste before',
  description: 'Paste before the start of each selection.',
  keybindings: [
    { key: 'Shift+p', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Paste after the end of each selection and select pasted text. */
export const pasteSelectAfter: ICommand & { readonly id: 'dance.paste.select.after' } = {
  id         : 'dance.paste.select.after',
  title      : 'Paste after and select',
  description: 'Paste after the end of each selection and select pasted text.',
  keybindings: [
    { key: 'Alt+p', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Paste before the start of each selection and select pasted text. */
export const pasteSelectBefore: ICommand & { readonly id: 'dance.paste.select.before' } = {
  id         : 'dance.paste.select.before',
  title      : 'Paste before and select',
  description: 'Paste before the start of each selection and select pasted text.',
  keybindings: [
    { key: 'Shift+Alt+p', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Replace selections with yanked text. */
export const pasteReplace: ICommand & { readonly id: 'dance.paste.replace' } = {
  id         : 'dance.paste.replace',
  title      : 'Replace',
  description: 'Replace selections with yanked text.',
  keybindings: [
    { key: 'Shift+r', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Replace selections with every yanked text. */
export const pasteReplaceEvery: ICommand & { readonly id: 'dance.paste.replace.every' } = {
  id         : 'dance.paste.replace.every',
  title      : 'Replace with every',
  description: 'Replace selections with every yanked text.',
  keybindings: [
    { key: 'Shift+Alt+r', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Replace each selected character with the next entered one. */
export const replaceCharacters: ICommand & { readonly id: 'dance.replace.characters' } = {
  id         : 'dance.replace.characters',
  title      : 'Replace character',
  description: 'Replace each selected character with the next entered one.',
  keybindings: [
    { key: 'r', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Join selected lines. */
export const join: ICommand & { readonly id: 'dance.join' } = {
  id         : 'dance.join',
  title      : 'Join lines',
  description: 'Join selected lines.',
  keybindings: [
    { key: 'Alt+j', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Join selected lines and select spaces inserted in place of line breaks. */
export const joinSelect: ICommand & { readonly id: 'dance.join.select' } = {
  id         : 'dance.join.select',
  title      : 'Join lines and select spaces',
  description: 'Join selected lines and select spaces inserted in place of line breaks.',
  keybindings: [
    { key: 'Shift+Alt+j', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Indent selected lines. */
export const indent: ICommand & { readonly id: 'dance.indent' } = {
  id         : 'dance.indent',
  title      : 'Indent',
  description: 'Indent selected lines.',
  keybindings: [
    { key: 'Shift+.', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Indent selected lines (including empty lines). */
export const indentWithEmpty: ICommand & { readonly id: 'dance.indent.withEmpty' } = {
  id         : 'dance.indent.withEmpty',
  title      : 'Indent (including empty)',
  description: 'Indent selected lines (including empty lines).',
  keybindings: [
    { key: 'Shift+Alt+.', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Deindent selected lines. */
export const deindent: ICommand & { readonly id: 'dance.deindent' } = {
  id         : 'dance.deindent',
  title      : 'Deindent',
  description: 'Deindent selected lines.',
  keybindings: [
    { key: 'Shift+Alt+,', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Deindent selected lines (and remove additional incomplete indent). */
export const deindentFurther: ICommand & { readonly id: 'dance.deindent.further' } = {
  id         : 'dance.deindent.further',
  title      : 'Deindent (including incomplete indent)',
  description: 'Deindent selected lines (and remove additional incomplete indent).',
  keybindings: [
    { key: 'Shift+,', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Transform to lowercase. */
export const toLowerCase: ICommand & { readonly id: 'dance.toLowerCase' } = {
  id         : 'dance.toLowerCase',
  title      : 'Transform to lowercase',
  description: 'Transform to lowercase.',
  keybindings: [
    { key: '`', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Transform to uppercase. */
export const toUpperCase: ICommand & { readonly id: 'dance.toUpperCase' } = {
  id         : 'dance.toUpperCase',
  title      : 'Transform to uppercase',
  description: 'Transform to uppercase.',
  keybindings: [
    { key: 'Shift+`', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Swap case. */
export const swapCase: ICommand & { readonly id: 'dance.swapCase' } = {
  id         : 'dance.swapCase',
  title      : 'Swap case',
  description: 'Swap case.',
  keybindings: [
    { key: 'Alt+`', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Pipe each selection to a program, and keeps it if the program returns 0. */
export const pipeFilter: ICommand & { readonly id: 'dance.pipe.filter' } = {
  id         : 'dance.pipe.filter',
  title      : 'Filter through pipe',
  description: 'Pipe each selection to a program, and keeps it if the program returns 0.',
  keybindings: [
    { key: 'Shift+4', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Pipe each selection to a command, and replaces it with its output. */
export const pipeReplace: ICommand & { readonly id: 'dance.pipe.replace' } = {
  id         : 'dance.pipe.replace',
  title      : 'Pipe and replace',
  description: 'Pipe each selection to a command, and replaces it with its output.',
  keybindings: [
    { key: 'Shift+\\', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Pipe each selection to a command, ignoring their results. */
export const pipeIgnore: ICommand & { readonly id: 'dance.pipe.ignore' } = {
  id         : 'dance.pipe.ignore',
  title      : 'Pipe',
  description: 'Pipe each selection to a command, ignoring their results.',
  keybindings: [
    { key: 'Shift+Alt+\\', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Pipe each selection to a command, appending the output after the selection. */
export const pipeAppend: ICommand & { readonly id: 'dance.pipe.append' } = {
  id         : 'dance.pipe.append',
  title      : 'Pipe and append',
  description: 'Pipe each selection to a command, appending the output after the selection.',
  keybindings: [
    { key: 'Shift+1', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Pipe each selection to a command, prepending the output before the selection. */
export const pipePrepend: ICommand & { readonly id: 'dance.pipe.prepend' } = {
  id         : 'dance.pipe.prepend',
  title      : 'Pipe and prepend',
  description: 'Pipe each selection to a command, prepending the output before the selection.',
  keybindings: [
    { key: 'Shift+Alt+1', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Undo. */
export const historyUndo: ICommand & { readonly id: 'dance.history.undo' } = {
  id         : 'dance.history.undo',
  title      : 'Undo',
  description: 'Undo.',
  keybindings: [
    { key: 'u', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Move backward in history. */
export const historyBackward: ICommand & { readonly id: 'dance.history.backward' } = {
  id         : 'dance.history.backward',
  title      : 'Move backward in history',
  description: 'Move backward in history.',
  keybindings: [
    { key: 'Alt+u', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Redo. */
export const historyRedo: ICommand & { readonly id: 'dance.history.redo' } = {
  id         : 'dance.history.redo',
  title      : 'Redo',
  description: 'Redo.',
  keybindings: [
    { key: 'Shift+u', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Move forward in history. */
export const historyForward: ICommand & { readonly id: 'dance.history.forward' } = {
  id         : 'dance.history.forward',
  title      : 'Move forward in history',
  description: 'Move forward in history.',
  keybindings: [
    { key: 'Shift+Alt+u', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Repeat last change. */
export const historyRepeat: ICommand & { readonly id: 'dance.history.repeat' } = {
  id         : 'dance.history.repeat',
  title      : 'Repeat last change',
  description: 'Repeat last change.',
  keybindings: [],
}
/** Repeat last selection change. */
export const historyRepeatSelection: ICommand & { readonly id: 'dance.history.repeat.selection' } = {
  id         : 'dance.history.repeat.selection',
  title      : 'Repeat last selection change',
  description: 'Repeat last selection change.',
  keybindings: [],
}
/** Repeat last edit change. */
export const historyRepeatEdit: ICommand & { readonly id: 'dance.history.repeat.edit' } = {
  id         : 'dance.history.repeat.edit',
  title      : 'Repeat last edit change',
  description: 'Repeat last edit change.',
  keybindings: [],
}
/** Start recording macro. */
export const macrosRecordStart: ICommand & { readonly id: 'dance.macros.record.start' } = {
  id         : 'dance.macros.record.start',
  title      : 'Start recording macro',
  description: 'Start recording macro.',
  keybindings: [
    { key: 'Shift+q', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Stop recording macro. */
export const macrosRecordStop: ICommand & { readonly id: 'dance.macros.record.stop' } = {
  id         : 'dance.macros.record.stop',
  title      : 'Stop recording macro',
  description: 'Stop recording macro.',
  keybindings: [
    { key: 'escape', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Play macro. */
export const macrosPlay: ICommand & { readonly id: 'dance.macros.play' } = {
  id         : 'dance.macros.play',
  title      : 'Play macro',
  description: 'Play macro.',
  keybindings: [
    { key: 'q', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Rotate each selection clockwise. */
export const rotate: ICommand & { readonly id: 'dance.rotate' } = {
  id         : 'dance.rotate',
  title      : 'Rotate',
  description: 'Rotate each selection clockwise.',
  keybindings: [
    { key: 'Shift+0', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Rotate each selection counter-clockwise. */
export const rotateBackwards: ICommand & { readonly id: 'dance.rotate.backwards' } = {
  id         : 'dance.rotate.backwards',
  title      : 'Rotate backwards',
  description: 'Rotate each selection counter-clockwise.',
  keybindings: [
    { key: 'Shift+9', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Rotate each selection (as well as its content) clockwise. */
export const rotateContent: ICommand & { readonly id: 'dance.rotate.content' } = {
  id         : 'dance.rotate.content',
  title      : 'Rotate selection content',
  description: 'Rotate each selection (as well as its content) clockwise.',
  keybindings: [
    { key: 'Shift+Alt+0', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Rotate each selection (as well as its content) counter-clockwise. */
export const rotateContentBackwards: ICommand & { readonly id: 'dance.rotate.content.backwards' } = {
  id         : 'dance.rotate.content.backwards',
  title      : 'Rotate selection content backwards',
  description: 'Rotate each selection (as well as its content) counter-clockwise.',
  keybindings: [
    { key: 'Shift+Alt+9', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Rotate each selection content clockwise, without changing selections. */
export const rotateContentOnly: ICommand & { readonly id: 'dance.rotate.contentOnly' } = {
  id         : 'dance.rotate.contentOnly',
  title      : 'Rotate content only',
  description: 'Rotate each selection content clockwise, without changing selections.',
  keybindings: [],
}
/** Rotate each selection content counter-clockwise, without changing selections. */
export const rotateContentOnlyBackwards: ICommand & { readonly id: 'dance.rotate.contentOnly.backwards' } = {
  id         : 'dance.rotate.contentOnly.backwards',
  title      : 'Rotate content only backwards',
  description: 'Rotate each selection content counter-clockwise, without changing selections.',
  keybindings: [],
}
/** Search for the given input string. */
export const search: ICommand & { readonly id: 'dance.search' } = {
  id         : 'dance.search',
  title      : 'Search',
  description: 'Search for the given input string.',
  keybindings: [
    { key: '/', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Search for the given input string before the current selections. */
export const searchBackwards: ICommand & { readonly id: 'dance.search.backwards' } = {
  id         : 'dance.search.backwards',
  title      : 'Search backwards',
  description: 'Search for the given input string before the current selections.',
  keybindings: [
    { key: 'Alt+/', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Search current selections (smart). */
export const searchSelectionSmart: ICommand & { readonly id: 'dance.search.selection.smart' } = {
  id         : 'dance.search.selection.smart',
  title      : 'Search current selections (smart)',
  description: 'Search current selections (smart).',
  keybindings: [
    { key: 'Shift+8', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Search current selections. */
export const searchSelection: ICommand & { readonly id: 'dance.search.selection' } = {
  id         : 'dance.search.selection',
  title      : 'Search current selections',
  description: 'Search current selections.',
  keybindings: [
    { key: 'Shift+Alt+8', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Select next match after the main selection. */
export const searchNext: ICommand & { readonly id: 'dance.search.next' } = {
  id         : 'dance.search.next',
  title      : 'Select next match',
  description: 'Select next match after the main selection.',
  keybindings: [
    { key: 'n', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Add a new selection with the next match after the main selection. */
export const searchNextAdd: ICommand & { readonly id: 'dance.search.next.add' } = {
  id         : 'dance.search.next.add',
  title      : 'Add next match',
  description: 'Add a new selection with the next match after the main selection.',
  keybindings: [
    { key: 'Shift+n', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Select previous match before the main selection. */
export const searchPrevious: ICommand & { readonly id: 'dance.search.previous' } = {
  id         : 'dance.search.previous',
  title      : 'Select previous match',
  description: 'Select previous match before the main selection.',
  keybindings: [
    { key: 'Alt+n', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Add a new selection with the previous match before the main selection. */
export const searchPreviousAdd: ICommand & { readonly id: 'dance.search.previous.add' } = {
  id         : 'dance.search.previous.add',
  title      : 'Add previous match',
  description: 'Add a new selection with the previous match before the main selection.',
  keybindings: [
    { key: 'Shift+Alt+n', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Select whole object. */
export const objectsSelect: ICommand & { readonly id: 'dance.objects.select' } = {
  id         : 'dance.objects.select',
  title      : 'Select whole object',
  description: 'Select whole object.',
  keybindings: [
    { key: 'Alt+a', when: 'editorTextFocus && dance.mode == \'normal\'' },
    { key: 'Alt+a', when: 'editorTextFocus && dance.mode == \'insert\'' },
  ],
}
/** Select inner object. */
export const objectsSelectInner: ICommand & { readonly id: 'dance.objects.select.inner' } = {
  id         : 'dance.objects.select.inner',
  title      : 'Select inner object',
  description: 'Select inner object.',
  keybindings: [
    { key: 'Alt+i', when: 'editorTextFocus && dance.mode == \'normal\'' },
    { key: 'Alt+i', when: 'editorTextFocus && dance.mode == \'insert\'' },
  ],
}
/** Select to the whole object start. */
export const objectsSelectToStart: ICommand & { readonly id: 'dance.objects.selectToStart' } = {
  id         : 'dance.objects.selectToStart',
  title      : 'Select to the whole object start',
  description: 'Select to the whole object start.',
  keybindings: [
    { key: '[', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Extend to the whole object start. */
export const objectsSelectToStartExtend: ICommand & { readonly id: 'dance.objects.selectToStart.extend' } = {
  id         : 'dance.objects.selectToStart.extend',
  title      : 'Extend to the whole object start',
  description: 'Extend to the whole object start.',
  keybindings: [
    { key: 'Shift+[', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Select to the whole object end. */
export const objectsSelectToEnd: ICommand & { readonly id: 'dance.objects.selectToEnd' } = {
  id         : 'dance.objects.selectToEnd',
  title      : 'Select to the whole object end',
  description: 'Select to the whole object end.',
  keybindings: [
    { key: ']', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Extend to the whole object end. */
export const objectsSelectToEndExtend: ICommand & { readonly id: 'dance.objects.selectToEnd.extend' } = {
  id         : 'dance.objects.selectToEnd.extend',
  title      : 'Extend to the whole object end',
  description: 'Extend to the whole object end.',
  keybindings: [
    { key: 'Shift+]', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Repeat object select. */
export const objectsSelectRepeat: ICommand & { readonly id: 'dance.objects.select.repeat' } = {
  id         : 'dance.objects.select.repeat',
  title      : 'Repeat object select',
  description: 'Repeat object select.',
  keybindings: [
    { key: 'Alt+.', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Shows prompt to jump somewhere */
export const goto: ICommand & { readonly id: 'dance.goto' } = {
  id         : 'dance.goto',
  title      : 'Go to...',
  description: 'Shows prompt to jump somewhere',
  keybindings: [
    { key: 'g', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Insert value in register. */
export const registersInsert: ICommand & { readonly id: 'dance.registers.insert' } = {
  id         : 'dance.registers.insert',
  title      : 'Insert value in register',
  description: 'Insert value in register.',
  keybindings: [
    { key: 'Ctrl+r', when: 'editorTextFocus && dance.mode == \'normal\'' },
    { key: 'Ctrl+r', when: 'editorTextFocus && dance.mode == \'insert\'' },
  ],
}
/** Select register for next command. */
export const registersSelect: ICommand & { readonly id: 'dance.registers.select' } = {
  id         : 'dance.registers.select',
  title      : 'Select register for next command',
  description: 'Select register for next command.',
  keybindings: [
    { key: 'Shift+\\\'', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Save selections. */
export const marksSaveSelections: ICommand & { readonly id: 'dance.marks.saveSelections' } = {
  id         : 'dance.marks.saveSelections',
  title      : 'Save selections',
  description: 'Save selections.',
  keybindings: [
    { key: 'Shift+z', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Restore selections. */
export const marksRestoreSelections: ICommand & { readonly id: 'dance.marks.restoreSelections' } = {
  id         : 'dance.marks.restoreSelections',
  title      : 'Restore selections',
  description: 'Restore selections.',
  keybindings: [
    { key: 'z', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Combine current selections with ones from register. */
export const marksCombineSelectionsFromCurrent: ICommand & { readonly id: 'dance.marks.combineSelections.fromCurrent' } = {
  id         : 'dance.marks.combineSelections.fromCurrent',
  title      : 'Combine current selections with ones from register',
  description: 'Combine current selections with ones from register.',
  keybindings: [
    { key: 'Shift+Alt+z', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Combine register selections with current ones. */
export const marksCombineSelectionsFromRegister: ICommand & { readonly id: 'dance.marks.combineSelections.fromRegister' } = {
  id         : 'dance.marks.combineSelections.fromRegister',
  title      : 'Combine register selections with current ones',
  description: 'Combine register selections with current ones.',
  keybindings: [
    { key: 'Alt+z', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Move left (extend). */
export const leftExtend: ICommand & { readonly id: 'dance.left.extend' } = {
  id         : 'dance.left.extend',
  title      : 'Move left (extend)',
  description: 'Move left (extend).',
  keybindings: [
    { key: 'Shift+left', when: 'editorTextFocus && dance.mode == \'normal\'' },
    { key: 'Shift+h', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Move right (extend). */
export const rightExtend: ICommand & { readonly id: 'dance.right.extend' } = {
  id         : 'dance.right.extend',
  title      : 'Move right (extend)',
  description: 'Move right (extend).',
  keybindings: [
    { key: 'Shift+right', when: 'editorTextFocus && dance.mode == \'normal\'' },
    { key: 'Shift+l', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Move up (extend). */
export const upExtend: ICommand & { readonly id: 'dance.up.extend' } = {
  id         : 'dance.up.extend',
  title      : 'Move up (extend)',
  description: 'Move up (extend).',
  keybindings: [
    { key: 'Shift+up', when: 'editorTextFocus && dance.mode == \'normal\'' },
    { key: 'Shift+k', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Move down (extend). */
export const downExtend: ICommand & { readonly id: 'dance.down.extend' } = {
  id         : 'dance.down.extend',
  title      : 'Move down (extend)',
  description: 'Move down (extend).',
  keybindings: [
    { key: 'Shift+down', when: 'editorTextFocus && dance.mode == \'normal\'' },
    { key: 'Shift+j', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Extend to the next character pressed, including it. */
export const selectToIncludedExtend: ICommand & { readonly id: 'dance.select.to.included.extend' } = {
  id         : 'dance.select.to.included.extend',
  title      : 'Extend to',
  description: 'Extend to the next character pressed, including it.',
  keybindings: [
    { key: 'Shift+f', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Extend with until the next character pressed, excluding it. */
export const selectToExcludedExtend: ICommand & { readonly id: 'dance.select.to.excluded.extend' } = {
  id         : 'dance.select.to.excluded.extend',
  title      : 'Extend until',
  description: 'Extend with until the next character pressed, excluding it.',
  keybindings: [
    { key: 'Shift+t', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Extend with line on which the end of each selection lies (or next line when end lies on an end-of-line). */
export const selectLineExtend: ICommand & { readonly id: 'dance.select.line.extend' } = {
  id         : 'dance.select.line.extend',
  title      : 'Extend with line',
  description: 'Extend with line on which the end of each selection lies (or next line when end lies on an end-of-line).',
  keybindings: [
    { key: 'Shift+x', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Extend to line beginning. */
export const selectToLineBeginExtend: ICommand & { readonly id: 'dance.select.toLineBegin.extend' } = {
  id         : 'dance.select.toLineBegin.extend',
  title      : 'Extend to line beginning',
  description: 'Extend to line beginning.',
  keybindings: [
    { key: 'Shift+Alt+h', when: 'editorTextFocus && dance.mode == \'normal\'' },
    { key: 'Shift+home', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Extend to line end. */
export const selectToLineEndExtend: ICommand & { readonly id: 'dance.select.toLineEnd.extend' } = {
  id         : 'dance.select.toLineEnd.extend',
  title      : 'Extend to line end',
  description: 'Extend to line end.',
  keybindings: [
    { key: 'Shift+Alt+l', when: 'editorTextFocus && dance.mode == \'normal\'' },
    { key: 'Shift+end', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Extend with enclosing characters. */
export const selectEnclosingExtend: ICommand & { readonly id: 'dance.select.enclosing.extend' } = {
  id         : 'dance.select.enclosing.extend',
  title      : 'Extend with enclosing characters',
  description: 'Extend with enclosing characters.',
  keybindings: [
    { key: 'Shift+m', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Extend with the word and following whitespaces on the right of the end of each selection. */
export const selectWordExtend: ICommand & { readonly id: 'dance.select.word.extend' } = {
  id         : 'dance.select.word.extend',
  title      : 'Extend to next word start',
  description: 'Extend with the word and following whitespaces on the right of the end of each selection.',
  keybindings: [
    { key: 'Shift+w', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Extend with preceding whitespaces and the word on the left of the end of each selection. */
export const selectWordPreviousExtend: ICommand & { readonly id: 'dance.select.word.previous.extend' } = {
  id         : 'dance.select.word.previous.extend',
  title      : 'Extend to previous word start',
  description: 'Extend with preceding whitespaces and the word on the left of the end of each selection.',
  keybindings: [
    { key: 'Shift+b', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Extend with preceding whitespaces and the word on the right of the end of each selection. */
export const selectWordEndExtend: ICommand & { readonly id: 'dance.select.word.end.extend' } = {
  id         : 'dance.select.word.end.extend',
  title      : 'Extend to next word end',
  description: 'Extend with preceding whitespaces and the word on the right of the end of each selection.',
  keybindings: [
    { key: 'Shift+e', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Extend with the non-whitespace word and following whitespaces on the right of the end of each selection. */
export const selectWordAltExtend: ICommand & { readonly id: 'dance.select.word.alt.extend' } = {
  id         : 'dance.select.word.alt.extend',
  title      : 'Extend to next non-whitespace word start',
  description: 'Extend with the non-whitespace word and following whitespaces on the right of the end of each selection.',
  keybindings: [
    { key: 'Shift+Alt+w', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Extend with preceding whitespaces and the non-whitespace word on the left of the end of each selection. */
export const selectWordAltPreviousExtend: ICommand & { readonly id: 'dance.select.word.alt.previous.extend' } = {
  id         : 'dance.select.word.alt.previous.extend',
  title      : 'Extend to previous non-whitespace word start',
  description: 'Extend with preceding whitespaces and the non-whitespace word on the left of the end of each selection.',
  keybindings: [
    { key: 'Shift+Alt+b', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Extend with preceding whitespaces and the non-whitespace word on the right of the end of each selection. */
export const selectWordAltEndExtend: ICommand & { readonly id: 'dance.select.word.alt.end.extend' } = {
  id         : 'dance.select.word.alt.end.extend',
  title      : 'Extend to next non-whitespace word end',
  description: 'Extend with preceding whitespaces and the non-whitespace word on the right of the end of each selection.',
  keybindings: [
    { key: 'Shift+Alt+e', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Search for the given input string (extend). */
export const searchExtend: ICommand & { readonly id: 'dance.search.extend' } = {
  id         : 'dance.search.extend',
  title      : 'Search (extend)',
  description: 'Search for the given input string (extend).',
  keybindings: [
    { key: 'Shift+/', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Search for the given input string before the current selections (extend). */
export const searchBackwardsExtend: ICommand & { readonly id: 'dance.search.backwards.extend' } = {
  id         : 'dance.search.backwards.extend',
  title      : 'Search backwards (extend)',
  description: 'Search for the given input string before the current selections (extend).',
  keybindings: [
    { key: 'Shift+Alt+/', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Shows prompt to jump somewhere */
export const gotoExtend: ICommand & { readonly id: 'dance.goto.extend' } = {
  id         : 'dance.goto.extend',
  title      : 'Go to... (extend)',
  description: 'Shows prompt to jump somewhere',
  keybindings: [
    { key: 'Shift+g', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Select to the next character pressed, including it. (backwards) */
export const selectToIncludedBackwards: ICommand & { readonly id: 'dance.select.to.included.backwards' } = {
  id         : 'dance.select.to.included.backwards',
  title      : 'Select to (backwards)',
  description: 'Select to the next character pressed, including it. (backwards)',
  keybindings: [
    { key: 'Alt+f', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Select until the next character pressed, excluding it. (backwards) */
export const selectToExcludedBackwards: ICommand & { readonly id: 'dance.select.to.excluded.backwards' } = {
  id         : 'dance.select.to.excluded.backwards',
  title      : 'Select until (backwards)',
  description: 'Select until the next character pressed, excluding it. (backwards)',
  keybindings: [
    { key: 'Alt+t', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Select enclosing characters. (backwards) */
export const selectEnclosingBackwards: ICommand & { readonly id: 'dance.select.enclosing.backwards' } = {
  id         : 'dance.select.enclosing.backwards',
  title      : 'Select enclosing characters (backwards)',
  description: 'Select enclosing characters. (backwards)',
  keybindings: [
    { key: 'Alt+m', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Extend to the next character pressed, including it. (backwards) */
export const selectToIncludedExtendBackwards: ICommand & { readonly id: 'dance.select.to.included.extend.backwards' } = {
  id         : 'dance.select.to.included.extend.backwards',
  title      : 'Extend to (backwards)',
  description: 'Extend to the next character pressed, including it. (backwards)',
  keybindings: [
    { key: 'Alt+Shift+f', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Extend with until the next character pressed, excluding it. (backwards) */
export const selectToExcludedExtendBackwards: ICommand & { readonly id: 'dance.select.to.excluded.extend.backwards' } = {
  id         : 'dance.select.to.excluded.extend.backwards',
  title      : 'Extend until (backwards)',
  description: 'Extend with until the next character pressed, excluding it. (backwards)',
  keybindings: [
    { key: 'Alt+Shift+t', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Extend with enclosing characters. (backwards) */
export const selectEnclosingExtendBackwards: ICommand & { readonly id: 'dance.select.enclosing.extend.backwards' } = {
  id         : 'dance.select.enclosing.extend.backwards',
  title      : 'Extend with enclosing characters (backwards)',
  description: 'Extend with enclosing characters. (backwards)',
  keybindings: [
    { key: 'Alt+Shift+m', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Select to the inner object start. */
export const objectsSelectToStartInner: ICommand & { readonly id: 'dance.objects.selectToStart.inner' } = {
  id         : 'dance.objects.selectToStart.inner',
  title      : 'Select to the inner object start',
  description: 'Select to the inner object start.',
  keybindings: [
    { key: 'Alt+[', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Extend to the inner object start. */
export const objectsSelectToStartExtendInner: ICommand & { readonly id: 'dance.objects.selectToStart.extend.inner' } = {
  id         : 'dance.objects.selectToStart.extend.inner',
  title      : 'Extend to the inner object start',
  description: 'Extend to the inner object start.',
  keybindings: [
    { key: 'Alt+Shift+[', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Select to the inner object end. */
export const objectsSelectToEndInner: ICommand & { readonly id: 'dance.objects.selectToEnd.inner' } = {
  id         : 'dance.objects.selectToEnd.inner',
  title      : 'Select to the inner object end',
  description: 'Select to the inner object end.',
  keybindings: [
    { key: 'Alt+]', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Extend to the inner object end. */
export const objectsSelectToEndExtendInner: ICommand & { readonly id: 'dance.objects.selectToEnd.extend.inner' } = {
  id         : 'dance.objects.selectToEnd.extend.inner',
  title      : 'Extend to the inner object end',
  description: 'Extend to the inner object end.',
  keybindings: [
    { key: 'Alt+Shift+]', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Adds 0 to the current counter for the next operation. */
export const count0: ICommand & { readonly id: 'dance.count.0' } = {
  id         : 'dance.count.0',
  title      : 'Count 0',
  description: 'Adds 0 to the current counter for the next operation.',
  keybindings: [
    { key: '0', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Adds 1 to the current counter for the next operation. */
export const count1: ICommand & { readonly id: 'dance.count.1' } = {
  id         : 'dance.count.1',
  title      : 'Count 1',
  description: 'Adds 1 to the current counter for the next operation.',
  keybindings: [
    { key: '1', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Adds 2 to the current counter for the next operation. */
export const count2: ICommand & { readonly id: 'dance.count.2' } = {
  id         : 'dance.count.2',
  title      : 'Count 2',
  description: 'Adds 2 to the current counter for the next operation.',
  keybindings: [
    { key: '2', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Adds 3 to the current counter for the next operation. */
export const count3: ICommand & { readonly id: 'dance.count.3' } = {
  id         : 'dance.count.3',
  title      : 'Count 3',
  description: 'Adds 3 to the current counter for the next operation.',
  keybindings: [
    { key: '3', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Adds 4 to the current counter for the next operation. */
export const count4: ICommand & { readonly id: 'dance.count.4' } = {
  id         : 'dance.count.4',
  title      : 'Count 4',
  description: 'Adds 4 to the current counter for the next operation.',
  keybindings: [
    { key: '4', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Adds 5 to the current counter for the next operation. */
export const count5: ICommand & { readonly id: 'dance.count.5' } = {
  id         : 'dance.count.5',
  title      : 'Count 5',
  description: 'Adds 5 to the current counter for the next operation.',
  keybindings: [
    { key: '5', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Adds 6 to the current counter for the next operation. */
export const count6: ICommand & { readonly id: 'dance.count.6' } = {
  id         : 'dance.count.6',
  title      : 'Count 6',
  description: 'Adds 6 to the current counter for the next operation.',
  keybindings: [
    { key: '6', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Adds 7 to the current counter for the next operation. */
export const count7: ICommand & { readonly id: 'dance.count.7' } = {
  id         : 'dance.count.7',
  title      : 'Count 7',
  description: 'Adds 7 to the current counter for the next operation.',
  keybindings: [
    { key: '7', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Adds 8 to the current counter for the next operation. */
export const count8: ICommand & { readonly id: 'dance.count.8' } = {
  id         : 'dance.count.8',
  title      : 'Count 8',
  description: 'Adds 8 to the current counter for the next operation.',
  keybindings: [
    { key: '8', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}
/** Adds 9 to the current counter for the next operation. */
export const count9: ICommand & { readonly id: 'dance.count.9' } = {
  id         : 'dance.count.9',
  title      : 'Count 9',
  description: 'Adds 9 to the current counter for the next operation.',
  keybindings: [
    { key: '9', when: 'editorTextFocus && dance.mode == \'normal\'' },
  ],
}

/** All defined commands. */
export const commands = {
  /** Toggles Dance key bindings. */
  toggle,
  /** Set Dance mode to Normal. */
  setNormal,
  /** Set Dance mode to Insert. */
  setInsert,
  /** Switches to normal mode temporarily. */
  tmpNormal,
  /** Switches to insert mode temporarily. */
  tmpInsert,
  /** Start insert before the current selections. */
  insertBefore,
  /** Start insert after the current selections. */
  insertAfter,
  /** Start insert at line start of each selection. */
  insertLineStart,
  /** Start insert at line end of each selection. */
  insertLineEnd,
  /** Create new line and start insert below. */
  insertNewLineBelow,
  /** Create new line and start insert above. */
  insertNewLineAbove,
  /** Add a new line below, without entering insert mode. */
  newLineBelow,
  /** Add a new line above, without entering insert mode. */
  newLineAbove,
  /** Repeat last insert-mode change. */
  repeatInsert,
  /** Move left. */
  left,
  /** Move right. */
  right,
  /** Move up. */
  up,
  /** Move down. */
  down,
  /** Select to the next character pressed, including it. */
  selectToIncluded,
  /** Select until the next character pressed, excluding it. */
  selectToExcluded,
  /** Select whole buffer. */
  selectBuffer,
  /** Select line on which the end of each selection lies (or next line when end lies on an end-of-line). */
  selectLine,
  /** Select to line beginning. */
  selectToLineBegin,
  /** Select to line end. */
  selectToLineEnd,
  /** Select enclosing characters. */
  selectEnclosing,
  /** Extend selections to contain full lines (including end-of-lines). */
  expandLines,
  /** Trim selections to only contain full lines (not including last end-of-line). */
  trimLines,
  /** Select the word and following whitespaces on the right of the end of each selection. */
  selectWord,
  /** Select preceding whitespaces and the word on the left of the end of each selection. */
  selectWordPrevious,
  /** Select preceding whitespaces and the word on the right of the end of each selection. */
  selectWordEnd,
  /** Select the non-whitespace word and following whitespaces on the right of the end of each selection. */
  selectWordAlt,
  /** Select preceding whitespaces and the non-whitespace word on the left of the end of each selection. */
  selectWordAltPrevious,
  /** Select preceding whitespaces and the non-whitespace word on the right of the end of each selection. */
  selectWordAltEnd,
  /** Select within current selections according to a RegExp. */
  select,
  /** Split within current selections according to a RegExp. */
  split,
  /** Split selections into lines. */
  splitLines,
  /** Select first and last characters of each selection. */
  selectFirstLast,
  /** Copy selection to next line. */
  selectCopy,
  /** Copy selection to previous line. */
  selectCopyBackwards,
  /** Reduce selections to their cursor. */
  selectionsReduce,
  /** Flip the direction of each selection. */
  selectionsFlip,
  /** Ensure selections are in forward direction (the active cursor is after the anchor). */
  selectionsForward,
  /** Ensure selections are in backward direction (the active cursor is before the anchor). */
  selectionsBackward,
  /** Clear selections (except main) */
  selectionsClear,
  /** Clear main selection. */
  selectionsClearMain,
  /** Keep selections that match a RegExp. */
  selectionsKeepMatching,
  /** Clear selections that match a RegExp. */
  selectionsClearMatching,
  /** Merge contiguous selections together, including across lines. */
  selectionsMerge,
  /** Align selections, aligning the cursor of each selection by inserting spaces before the first character of each selection. */
  selectionsAlign,
  /** Copy the indentation of the main selection (or the count one if a count is given) to all other ones. */
  selectionsAlignCopy,
  /** Yank and delete selections. */
  deleteYank,
  /** Yank, delete and enter insert mode. */
  deleteInsertYank,
  /** Delete selections without yanking. */
  deleteNoYank,
  /** Delete selections without yanking and enter insert mode. */
  deleteInsertNoYank,
  /** Yank selections. */
  yank,
  /** Paste after the end of each selection. */
  pasteAfter,
  /** Paste before the start of each selection. */
  pasteBefore,
  /** Paste after the end of each selection and select pasted text. */
  pasteSelectAfter,
  /** Paste before the start of each selection and select pasted text. */
  pasteSelectBefore,
  /** Replace selections with yanked text. */
  pasteReplace,
  /** Replace selections with every yanked text. */
  pasteReplaceEvery,
  /** Replace each selected character with the next entered one. */
  replaceCharacters,
  /** Join selected lines. */
  join,
  /** Join selected lines and select spaces inserted in place of line breaks. */
  joinSelect,
  /** Indent selected lines. */
  indent,
  /** Indent selected lines (including empty lines). */
  indentWithEmpty,
  /** Deindent selected lines. */
  deindent,
  /** Deindent selected lines (and remove additional incomplete indent). */
  deindentFurther,
  /** Transform to lowercase. */
  toLowerCase,
  /** Transform to uppercase. */
  toUpperCase,
  /** Swap case. */
  swapCase,
  /** Pipe each selection to a program, and keeps it if the program returns 0. */
  pipeFilter,
  /** Pipe each selection to a command, and replaces it with its output. */
  pipeReplace,
  /** Pipe each selection to a command, ignoring their results. */
  pipeIgnore,
  /** Pipe each selection to a command, appending the output after the selection. */
  pipeAppend,
  /** Pipe each selection to a command, prepending the output before the selection. */
  pipePrepend,
  /** Undo. */
  historyUndo,
  /** Move backward in history. */
  historyBackward,
  /** Redo. */
  historyRedo,
  /** Move forward in history. */
  historyForward,
  /** Repeat last change. */
  historyRepeat,
  /** Repeat last selection change. */
  historyRepeatSelection,
  /** Repeat last edit change. */
  historyRepeatEdit,
  /** Start recording macro. */
  macrosRecordStart,
  /** Stop recording macro. */
  macrosRecordStop,
  /** Play macro. */
  macrosPlay,
  /** Rotate each selection clockwise. */
  rotate,
  /** Rotate each selection counter-clockwise. */
  rotateBackwards,
  /** Rotate each selection (as well as its content) clockwise. */
  rotateContent,
  /** Rotate each selection (as well as its content) counter-clockwise. */
  rotateContentBackwards,
  /** Rotate each selection content clockwise, without changing selections. */
  rotateContentOnly,
  /** Rotate each selection content counter-clockwise, without changing selections. */
  rotateContentOnlyBackwards,
  /** Search for the given input string. */
  search,
  /** Search for the given input string before the current selections. */
  searchBackwards,
  /** Search current selections (smart). */
  searchSelectionSmart,
  /** Search current selections. */
  searchSelection,
  /** Select next match after the main selection. */
  searchNext,
  /** Add a new selection with the next match after the main selection. */
  searchNextAdd,
  /** Select previous match before the main selection. */
  searchPrevious,
  /** Add a new selection with the previous match before the main selection. */
  searchPreviousAdd,
  /** Select whole object. */
  objectsSelect,
  /** Select inner object. */
  objectsSelectInner,
  /** Select to the whole object start. */
  objectsSelectToStart,
  /** Extend to the whole object start. */
  objectsSelectToStartExtend,
  /** Select to the whole object end. */
  objectsSelectToEnd,
  /** Extend to the whole object end. */
  objectsSelectToEndExtend,
  /** Repeat object select. */
  objectsSelectRepeat,
  /** Shows prompt to jump somewhere */
  goto,
  /** Insert value in register. */
  registersInsert,
  /** Select register for next command. */
  registersSelect,
  /** Save selections. */
  marksSaveSelections,
  /** Restore selections. */
  marksRestoreSelections,
  /** Combine current selections with ones from register. */
  marksCombineSelectionsFromCurrent,
  /** Combine register selections with current ones. */
  marksCombineSelectionsFromRegister,
  /** Move left (extend). */
  leftExtend,
  /** Move right (extend). */
  rightExtend,
  /** Move up (extend). */
  upExtend,
  /** Move down (extend). */
  downExtend,
  /** Extend to the next character pressed, including it. */
  selectToIncludedExtend,
  /** Extend with until the next character pressed, excluding it. */
  selectToExcludedExtend,
  /** Extend with line on which the end of each selection lies (or next line when end lies on an end-of-line). */
  selectLineExtend,
  /** Extend to line beginning. */
  selectToLineBeginExtend,
  /** Extend to line end. */
  selectToLineEndExtend,
  /** Extend with enclosing characters. */
  selectEnclosingExtend,
  /** Extend with the word and following whitespaces on the right of the end of each selection. */
  selectWordExtend,
  /** Extend with preceding whitespaces and the word on the left of the end of each selection. */
  selectWordPreviousExtend,
  /** Extend with preceding whitespaces and the word on the right of the end of each selection. */
  selectWordEndExtend,
  /** Extend with the non-whitespace word and following whitespaces on the right of the end of each selection. */
  selectWordAltExtend,
  /** Extend with preceding whitespaces and the non-whitespace word on the left of the end of each selection. */
  selectWordAltPreviousExtend,
  /** Extend with preceding whitespaces and the non-whitespace word on the right of the end of each selection. */
  selectWordAltEndExtend,
  /** Search for the given input string (extend). */
  searchExtend,
  /** Search for the given input string before the current selections (extend). */
  searchBackwardsExtend,
  /** Shows prompt to jump somewhere */
  gotoExtend,
  /** Select to the next character pressed, including it. (backwards) */
  selectToIncludedBackwards,
  /** Select until the next character pressed, excluding it. (backwards) */
  selectToExcludedBackwards,
  /** Select enclosing characters. (backwards) */
  selectEnclosingBackwards,
  /** Extend to the next character pressed, including it. (backwards) */
  selectToIncludedExtendBackwards,
  /** Extend with until the next character pressed, excluding it. (backwards) */
  selectToExcludedExtendBackwards,
  /** Extend with enclosing characters. (backwards) */
  selectEnclosingExtendBackwards,
  /** Select to the inner object start. */
  objectsSelectToStartInner,
  /** Extend to the inner object start. */
  objectsSelectToStartExtendInner,
  /** Select to the inner object end. */
  objectsSelectToEndInner,
  /** Extend to the inner object end. */
  objectsSelectToEndExtendInner,
  /** Adds 0 to the current counter for the next operation. */
  count0,
  /** Adds 1 to the current counter for the next operation. */
  count1,
  /** Adds 2 to the current counter for the next operation. */
  count2,
  /** Adds 3 to the current counter for the next operation. */
  count3,
  /** Adds 4 to the current counter for the next operation. */
  count4,
  /** Adds 5 to the current counter for the next operation. */
  count5,
  /** Adds 6 to the current counter for the next operation. */
  count6,
  /** Adds 7 to the current counter for the next operation. */
  count7,
  /** Adds 8 to the current counter for the next operation. */
  count8,
  /** Adds 9 to the current counter for the next operation. */
  count9
}

/** An enum which maps command names to command IDs. */
export const enum Command {
  /** Toggles Dance key bindings. */
  toggle = 'dance.toggle',
  /** Set Dance mode to Normal. */
  setNormal = 'dance.set.normal',
  /** Set Dance mode to Insert. */
  setInsert = 'dance.set.insert',
  /** Switches to normal mode temporarily. */
  tmpNormal = 'dance.tmp.normal',
  /** Switches to insert mode temporarily. */
  tmpInsert = 'dance.tmp.insert',
  /** Start insert before the current selections. */
  insertBefore = 'dance.insert.before',
  /** Start insert after the current selections. */
  insertAfter = 'dance.insert.after',
  /** Start insert at line start of each selection. */
  insertLineStart = 'dance.insert.lineStart',
  /** Start insert at line end of each selection. */
  insertLineEnd = 'dance.insert.lineEnd',
  /** Create new line and start insert below. */
  insertNewLineBelow = 'dance.insert.newLine.below',
  /** Create new line and start insert above. */
  insertNewLineAbove = 'dance.insert.newLine.above',
  /** Add a new line below, without entering insert mode. */
  newLineBelow = 'dance.newLine.below',
  /** Add a new line above, without entering insert mode. */
  newLineAbove = 'dance.newLine.above',
  /** Repeat last insert-mode change. */
  repeatInsert = 'dance.repeat.insert',
  /** Move left. */
  left = 'dance.left',
  /** Move right. */
  right = 'dance.right',
  /** Move up. */
  up = 'dance.up',
  /** Move down. */
  down = 'dance.down',
  /** Select to the next character pressed, including it. */
  selectToIncluded = 'dance.select.to.included',
  /** Select until the next character pressed, excluding it. */
  selectToExcluded = 'dance.select.to.excluded',
  /** Select whole buffer. */
  selectBuffer = 'dance.select.buffer',
  /** Select line on which the end of each selection lies (or next line when end lies on an end-of-line). */
  selectLine = 'dance.select.line',
  /** Select to line beginning. */
  selectToLineBegin = 'dance.select.toLineBegin',
  /** Select to line end. */
  selectToLineEnd = 'dance.select.toLineEnd',
  /** Select enclosing characters. */
  selectEnclosing = 'dance.select.enclosing',
  /** Extend selections to contain full lines (including end-of-lines). */
  expandLines = 'dance.expandLines',
  /** Trim selections to only contain full lines (not including last end-of-line). */
  trimLines = 'dance.trimLines',
  /** Select the word and following whitespaces on the right of the end of each selection. */
  selectWord = 'dance.select.word',
  /** Select preceding whitespaces and the word on the left of the end of each selection. */
  selectWordPrevious = 'dance.select.word.previous',
  /** Select preceding whitespaces and the word on the right of the end of each selection. */
  selectWordEnd = 'dance.select.word.end',
  /** Select the non-whitespace word and following whitespaces on the right of the end of each selection. */
  selectWordAlt = 'dance.select.word.alt',
  /** Select preceding whitespaces and the non-whitespace word on the left of the end of each selection. */
  selectWordAltPrevious = 'dance.select.word.alt.previous',
  /** Select preceding whitespaces and the non-whitespace word on the right of the end of each selection. */
  selectWordAltEnd = 'dance.select.word.alt.end',
  /** Select within current selections according to a RegExp. */
  select = 'dance.select',
  /** Split within current selections according to a RegExp. */
  split = 'dance.split',
  /** Split selections into lines. */
  splitLines = 'dance.split.lines',
  /** Select first and last characters of each selection. */
  selectFirstLast = 'dance.select.firstLast',
  /** Copy selection to next line. */
  selectCopy = 'dance.select.copy',
  /** Copy selection to previous line. */
  selectCopyBackwards = 'dance.select.copy.backwards',
  /** Reduce selections to their cursor. */
  selectionsReduce = 'dance.selections.reduce',
  /** Flip the direction of each selection. */
  selectionsFlip = 'dance.selections.flip',
  /** Ensure selections are in forward direction (the active cursor is after the anchor). */
  selectionsForward = 'dance.selections.forward',
  /** Ensure selections are in backward direction (the active cursor is before the anchor). */
  selectionsBackward = 'dance.selections.backward',
  /** Clear selections (except main) */
  selectionsClear = 'dance.selections.clear',
  /** Clear main selection. */
  selectionsClearMain = 'dance.selections.clearMain',
  /** Keep selections that match a RegExp. */
  selectionsKeepMatching = 'dance.selections.keepMatching',
  /** Clear selections that match a RegExp. */
  selectionsClearMatching = 'dance.selections.clearMatching',
  /** Merge contiguous selections together, including across lines. */
  selectionsMerge = 'dance.selections.merge',
  /** Align selections, aligning the cursor of each selection by inserting spaces before the first character of each selection. */
  selectionsAlign = 'dance.selections.align',
  /** Copy the indentation of the main selection (or the count one if a count is given) to all other ones. */
  selectionsAlignCopy = 'dance.selections.align.copy',
  /** Yank and delete selections. */
  deleteYank = 'dance.delete.yank',
  /** Yank, delete and enter insert mode. */
  deleteInsertYank = 'dance.delete.insert.yank',
  /** Delete selections without yanking. */
  deleteNoYank = 'dance.delete.noYank',
  /** Delete selections without yanking and enter insert mode. */
  deleteInsertNoYank = 'dance.delete.insert.noYank',
  /** Yank selections. */
  yank = 'dance.yank',
  /** Paste after the end of each selection. */
  pasteAfter = 'dance.paste.after',
  /** Paste before the start of each selection. */
  pasteBefore = 'dance.paste.before',
  /** Paste after the end of each selection and select pasted text. */
  pasteSelectAfter = 'dance.paste.select.after',
  /** Paste before the start of each selection and select pasted text. */
  pasteSelectBefore = 'dance.paste.select.before',
  /** Replace selections with yanked text. */
  pasteReplace = 'dance.paste.replace',
  /** Replace selections with every yanked text. */
  pasteReplaceEvery = 'dance.paste.replace.every',
  /** Replace each selected character with the next entered one. */
  replaceCharacters = 'dance.replace.characters',
  /** Join selected lines. */
  join = 'dance.join',
  /** Join selected lines and select spaces inserted in place of line breaks. */
  joinSelect = 'dance.join.select',
  /** Indent selected lines. */
  indent = 'dance.indent',
  /** Indent selected lines (including empty lines). */
  indentWithEmpty = 'dance.indent.withEmpty',
  /** Deindent selected lines. */
  deindent = 'dance.deindent',
  /** Deindent selected lines (and remove additional incomplete indent). */
  deindentFurther = 'dance.deindent.further',
  /** Transform to lowercase. */
  toLowerCase = 'dance.toLowerCase',
  /** Transform to uppercase. */
  toUpperCase = 'dance.toUpperCase',
  /** Swap case. */
  swapCase = 'dance.swapCase',
  /** Pipe each selection to a program, and keeps it if the program returns 0. */
  pipeFilter = 'dance.pipe.filter',
  /** Pipe each selection to a command, and replaces it with its output. */
  pipeReplace = 'dance.pipe.replace',
  /** Pipe each selection to a command, ignoring their results. */
  pipeIgnore = 'dance.pipe.ignore',
  /** Pipe each selection to a command, appending the output after the selection. */
  pipeAppend = 'dance.pipe.append',
  /** Pipe each selection to a command, prepending the output before the selection. */
  pipePrepend = 'dance.pipe.prepend',
  /** Undo. */
  historyUndo = 'dance.history.undo',
  /** Move backward in history. */
  historyBackward = 'dance.history.backward',
  /** Redo. */
  historyRedo = 'dance.history.redo',
  /** Move forward in history. */
  historyForward = 'dance.history.forward',
  /** Repeat last change. */
  historyRepeat = 'dance.history.repeat',
  /** Repeat last selection change. */
  historyRepeatSelection = 'dance.history.repeat.selection',
  /** Repeat last edit change. */
  historyRepeatEdit = 'dance.history.repeat.edit',
  /** Start recording macro. */
  macrosRecordStart = 'dance.macros.record.start',
  /** Stop recording macro. */
  macrosRecordStop = 'dance.macros.record.stop',
  /** Play macro. */
  macrosPlay = 'dance.macros.play',
  /** Rotate each selection clockwise. */
  rotate = 'dance.rotate',
  /** Rotate each selection counter-clockwise. */
  rotateBackwards = 'dance.rotate.backwards',
  /** Rotate each selection (as well as its content) clockwise. */
  rotateContent = 'dance.rotate.content',
  /** Rotate each selection (as well as its content) counter-clockwise. */
  rotateContentBackwards = 'dance.rotate.content.backwards',
  /** Rotate each selection content clockwise, without changing selections. */
  rotateContentOnly = 'dance.rotate.contentOnly',
  /** Rotate each selection content counter-clockwise, without changing selections. */
  rotateContentOnlyBackwards = 'dance.rotate.contentOnly.backwards',
  /** Search for the given input string. */
  search = 'dance.search',
  /** Search for the given input string before the current selections. */
  searchBackwards = 'dance.search.backwards',
  /** Search current selections (smart). */
  searchSelectionSmart = 'dance.search.selection.smart',
  /** Search current selections. */
  searchSelection = 'dance.search.selection',
  /** Select next match after the main selection. */
  searchNext = 'dance.search.next',
  /** Add a new selection with the next match after the main selection. */
  searchNextAdd = 'dance.search.next.add',
  /** Select previous match before the main selection. */
  searchPrevious = 'dance.search.previous',
  /** Add a new selection with the previous match before the main selection. */
  searchPreviousAdd = 'dance.search.previous.add',
  /** Select whole object. */
  objectsSelect = 'dance.objects.select',
  /** Select inner object. */
  objectsSelectInner = 'dance.objects.select.inner',
  /** Select to the whole object start. */
  objectsSelectToStart = 'dance.objects.selectToStart',
  /** Extend to the whole object start. */
  objectsSelectToStartExtend = 'dance.objects.selectToStart.extend',
  /** Select to the whole object end. */
  objectsSelectToEnd = 'dance.objects.selectToEnd',
  /** Extend to the whole object end. */
  objectsSelectToEndExtend = 'dance.objects.selectToEnd.extend',
  /** Repeat object select. */
  objectsSelectRepeat = 'dance.objects.select.repeat',
  /** Shows prompt to jump somewhere */
  goto = 'dance.goto',
  /** Insert value in register. */
  registersInsert = 'dance.registers.insert',
  /** Select register for next command. */
  registersSelect = 'dance.registers.select',
  /** Save selections. */
  marksSaveSelections = 'dance.marks.saveSelections',
  /** Restore selections. */
  marksRestoreSelections = 'dance.marks.restoreSelections',
  /** Combine current selections with ones from register. */
  marksCombineSelectionsFromCurrent = 'dance.marks.combineSelections.fromCurrent',
  /** Combine register selections with current ones. */
  marksCombineSelectionsFromRegister = 'dance.marks.combineSelections.fromRegister',
  /** Move left (extend). */
  leftExtend = 'dance.left.extend',
  /** Move right (extend). */
  rightExtend = 'dance.right.extend',
  /** Move up (extend). */
  upExtend = 'dance.up.extend',
  /** Move down (extend). */
  downExtend = 'dance.down.extend',
  /** Extend to the next character pressed, including it. */
  selectToIncludedExtend = 'dance.select.to.included.extend',
  /** Extend with until the next character pressed, excluding it. */
  selectToExcludedExtend = 'dance.select.to.excluded.extend',
  /** Extend with line on which the end of each selection lies (or next line when end lies on an end-of-line). */
  selectLineExtend = 'dance.select.line.extend',
  /** Extend to line beginning. */
  selectToLineBeginExtend = 'dance.select.toLineBegin.extend',
  /** Extend to line end. */
  selectToLineEndExtend = 'dance.select.toLineEnd.extend',
  /** Extend with enclosing characters. */
  selectEnclosingExtend = 'dance.select.enclosing.extend',
  /** Extend with the word and following whitespaces on the right of the end of each selection. */
  selectWordExtend = 'dance.select.word.extend',
  /** Extend with preceding whitespaces and the word on the left of the end of each selection. */
  selectWordPreviousExtend = 'dance.select.word.previous.extend',
  /** Extend with preceding whitespaces and the word on the right of the end of each selection. */
  selectWordEndExtend = 'dance.select.word.end.extend',
  /** Extend with the non-whitespace word and following whitespaces on the right of the end of each selection. */
  selectWordAltExtend = 'dance.select.word.alt.extend',
  /** Extend with preceding whitespaces and the non-whitespace word on the left of the end of each selection. */
  selectWordAltPreviousExtend = 'dance.select.word.alt.previous.extend',
  /** Extend with preceding whitespaces and the non-whitespace word on the right of the end of each selection. */
  selectWordAltEndExtend = 'dance.select.word.alt.end.extend',
  /** Search for the given input string (extend). */
  searchExtend = 'dance.search.extend',
  /** Search for the given input string before the current selections (extend). */
  searchBackwardsExtend = 'dance.search.backwards.extend',
  /** Shows prompt to jump somewhere */
  gotoExtend = 'dance.goto.extend',
  /** Select to the next character pressed, including it. (backwards) */
  selectToIncludedBackwards = 'dance.select.to.included.backwards',
  /** Select until the next character pressed, excluding it. (backwards) */
  selectToExcludedBackwards = 'dance.select.to.excluded.backwards',
  /** Select enclosing characters. (backwards) */
  selectEnclosingBackwards = 'dance.select.enclosing.backwards',
  /** Extend to the next character pressed, including it. (backwards) */
  selectToIncludedExtendBackwards = 'dance.select.to.included.extend.backwards',
  /** Extend with until the next character pressed, excluding it. (backwards) */
  selectToExcludedExtendBackwards = 'dance.select.to.excluded.extend.backwards',
  /** Extend with enclosing characters. (backwards) */
  selectEnclosingExtendBackwards = 'dance.select.enclosing.extend.backwards',
  /** Select to the inner object start. */
  objectsSelectToStartInner = 'dance.objects.selectToStart.inner',
  /** Extend to the inner object start. */
  objectsSelectToStartExtendInner = 'dance.objects.selectToStart.extend.inner',
  /** Select to the inner object end. */
  objectsSelectToEndInner = 'dance.objects.selectToEnd.inner',
  /** Extend to the inner object end. */
  objectsSelectToEndExtendInner = 'dance.objects.selectToEnd.extend.inner',
  /** Adds 0 to the current counter for the next operation. */
  count0 = 'dance.count.0',
  /** Adds 1 to the current counter for the next operation. */
  count1 = 'dance.count.1',
  /** Adds 2 to the current counter for the next operation. */
  count2 = 'dance.count.2',
  /** Adds 3 to the current counter for the next operation. */
  count3 = 'dance.count.3',
  /** Adds 4 to the current counter for the next operation. */
  count4 = 'dance.count.4',
  /** Adds 5 to the current counter for the next operation. */
  count5 = 'dance.count.5',
  /** Adds 6 to the current counter for the next operation. */
  count6 = 'dance.count.6',
  /** Adds 7 to the current counter for the next operation. */
  count7 = 'dance.count.7',
  /** Adds 8 to the current counter for the next operation. */
  count8 = 'dance.count.8',
  /** Adds 9 to the current counter for the next operation. */
  count9 = 'dance.count.9'
}
